TLDV_API_KEY = "8b18d2e3-233e-40ca-8e98-7c578f18a1bf"
GOOGLE_CLIENT_ID = "654586647322-lgrac94ljoj0m3rofon1pvqjpkjpi9s6.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
OPENAI_API_KEY = "sk-proj-LJfCyoHqaWi4ieWHkastT3BlbkFJFouywwMq22BR2zyOfmH6"
REDIRECT_URI = "http://localhost:8501/"